const fs = require('fs');

function generateMarkdownReport(reportObj) {
  let md = `# 🤖 AutoQA - Quality Engineering Report\n\n`;
  
  // Tests Summary
  const passed = reportObj.tests.filter(t => t.status === "Passed").length;
  const failed = reportObj.tests.filter(t => t.status === "Failed").length;
  
  const hasRealDefects = reportObj.tests.some(t => t.triage?.classification === "Broken");
  const overallDecision = hasRealDefects ? "❌ No-Go (Real defects detected)" : "✅ Go (Tests passed/healed safely)";

  md += `## Overall Decision: ${overallDecision}\n`;
  md += `**Test Summary:** ${passed} Passed | ${failed} Failed\n\n`;

  md += `### Intent Tests\n`;
  reportObj.tests.forEach(t => {
    md += `#### ${t.status === 'Passed' ? '✅' : '❌'} [${t.id}] ${t.intent}\n`;
    if (t.healedSteps && t.healedSteps.length > 0) {
      md += `**Healed Steps:**\n`;
      t.healedSteps.forEach(s => {
        md += `- \`${s.step}\` -> *${s.reasoning}*\n`;
      });
    }
    if (t.status === "Failed") {
      md += `**Error:** \`${t.error}\`\n`;
      if (t.triage) {
        md += `**Triage Analysis (${t.triage.classification}):** ${t.triage.reasoning}\n`;
      }
    }
    md += `\n`;
  });

  // Scanners Summary
  md += `### 🛡️ Security (OWASP ZAP)\n`;
  if (reportObj.security) {
    reportObj.security.forEach(s => {
      md += `- [${s.risk}] ${s.alert}\n`;
    });
  } else {
    md += `No security data available.\n`;
  }
  md += `\n`;

  md += `### ♿ Accessibility (axe-core)\n`;
  if (reportObj.accessibility && reportObj.accessibility.length > 0) {
    reportObj.accessibility.forEach(a => {
      if (a.error) {
        md += `- ⚠️ Axe scan failed: ${a.error}\n`;
      } else {
        md += `- [${a.impact}] ${a.id}: ${a.description}\n`;
      }
    });
  } else {
    md += `✅ No accessibility violations detected.\n`;
  }
  md += `\n`;

  md += `### ⚡ Performance (Lighthouse)\n`;
  if (reportObj.performance && !reportObj.performance.error) {
    md += `- Score: ${reportObj.performance.score * 100} / 100\n`;
    md += `- FCP: ${reportObj.performance.metrics.FCP}\n`;
    md += `- LCP: ${reportObj.performance.metrics.LCP}\n`;
    md += `*Note: ${reportObj.performance.note}*\n`;
  } else {
    md += `No performance data available.\n`;
  }
  md += `\n`;

  md += `---\n*Generated by Autonomous Quality Engineering MVP*\n`;
  
  fs.writeFileSync("pr_comment_report.md", md);
  console.log("Report generated at pr_comment_report.md");
}

module.exports = { generateMarkdownReport };
